# Generated by Django 4.1.5 on 2023-01-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_light_meter_id_measure_light_meter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measure',
            old_name='light_meter',
            new_name='light_meter_id',
        ),
    ]
