# Generated by Django 4.1.5 on 2023-01-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_light_meter_measure_light_meter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='light_meter_id',
            field=models.ForeignKey(db_column='light_meter_id', on_delete=django.db.models.deletion.PROTECT, to='api.lightmeter'),
        ),
    ]
