# Generated by Django 4.1.5 on 2023-01-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_measure_light_meter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightmeter',
            name='key',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='key',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
