# Generated by Django 4.1.5 on 2023-01-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lightmeter_key_measure_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightmeter',
            name='key',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='measure',
            name='key',
            field=models.CharField(max_length=256),
        ),
    ]
