# Generated by Django 4.1.5 on 2023-01-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_lightmeter_key_alter_measure_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightmeter',
            name='key',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='key',
        ),
    ]
